# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

general:
  branches:
    ignore:
      - gh-pages

orbs:
  browser-tools: circleci/browser-tools@1.2.4

defaults: &defaults
  docker:
    - image: cimg/node:22.2.0-browsers
      environment:
        CHROME_BIN: /usr/bin/google-chrome


jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: npm ci
      - run: npm run ng -- test @muziehdesign/forms
  build:
    <<: *defaults
    steps:
      - checkout
      #- run: npm run lint
      - run:
          name: 'version'
          command: |
            bash ./version.sh ${CIRCLE_BUILD_NUM} ${CIRCLE_BRANCH}
      - run:
          name: 'version muziehdesign/forms'
          command: |
            bash ./../../../version.sh ${CIRCLE_BUILD_NUM} ${CIRCLE_BRANCH}
          working_directory: ./projects/muziehdesign/forms
      - run: npm ci
      - run: npm run ng -- build @muziehdesign/forms
      - run: npm run build
      - store_artifacts:
          path: /dist/muziehdesign/forms
          destination: forms
      - persist_to_workspace:
          root: .
          paths:
            - dist
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'npm publish prep'
          command: |
            touch .npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: 
          name: 'npm publish'
          command: |
            if [ "$BRANCH" = "master" ] || [ "$BRANCH" = "develop" ] ||  [[ "$BRANCH" = \release\/* ]]; then
              echo "publishing non-beta package"
              npm publish ./dist/muziehdesign/forms
            else
              echo "publishing beta package"
              npm publish ./dist/muziehdesign/forms --tag beta
            fi

workflows:
  publish:
    jobs:
      - test
      - build
      - publish:
          requires:
            - test
            - build
